name: lifem

services:

  # ── Backend ───────────────────────────────────────────────────────────────────

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lifem-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lifem?useLegacyDatetimeCode=false&serverTimezone=Asia/Manila&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Admin1234}
      ENCRYPTION_PASSWORD: ${ENCRYPTION_PASSWORD:-idnaheim}
      ENCRYPTION_SALT: ${ENCRYPTION_SALT:-bc4ec87caf751f440668f85f0b406126c2806a1ed44e1efe46bfbb5ef8a70b24}
      TZ: Asia/Manila

  # ── Frontend ──────────────────────────────────────────────────────────────────

  frontend:
    build:
      context: ../frontend-lifem
      dockerfile: Dockerfile
    container_name: lifem-frontend
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"

