services:
  api:
    build: .
    container_name: lifem-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lifem?useLegacyDatetimeCode=false&serverTimezone=Asia/Manila
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Admin1234
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ../frontend-lifem
    container_name: lifem-frontend
    ports:
      - "80:80"
    depends_on:
      - api
